const FACTOR_SODIUM = 500;
const FACTOR_CHOLESTEROL = 10;
const FACTOR_CARBOHYDRATES = 130;
const FACTOR_GLYCEMIC_LOAD = 5;
const FACTOR_FAT = 66;
const FACTOR_PROTEINS = 15;
const FACTOR_CALORIES = 400;

module.exports = {
  FACTOR_SODIUM,
  FACTOR_CHOLESTEROL,
  FACTOR_CARBOHYDRATES,
  FACTOR_GLYCEMIC_LOAD,
  FACTOR_FAT,
  FACTOR_PROTEINS,
  FACTOR_CALORIES,
};
