const FACTOR_SODIUM = 115
const FACTOR_CHOLESTEROL = 10
const FACTOR_CARBOHYDRATES = 12
const FACTOR_GLYCEMIC_LOAD = 5
const FACTOR_FAT = 25
const FACTOR_PROTEINS = 15

module.exports = {
  FACTOR_SODIUM,
  FACTOR_CHOLESTEROL,
  FACTOR_CARBOHYDRATES,
  FACTOR_GLYCEMIC_LOAD,
  FACTOR_FAT,
  FACTOR_PROTEINS,
}